### ISSUE TITLE
Borders on inputs look weird

### ISSUE THREAD

**Issue by thakkarparth007** [coderick14/DeltaInductions2016#2]
The borders of inputs look ugly - you could either set border to 0 explicitly (the browser ruins the inputs if you don't set border when setting border radius), or to some non-zero number.

Also, there's a highlight that is displayed around the inputs, and the highlight clearly doesn't go well with the shape of the input. Look up how to get rid of that.

**Comment by coderick14** [comment]
I set the borders explicitly to some non-zero value now.
